// lib/chains.ts
// Verified burn addresses — hardcoded, never dynamic

export const EVM_BURN_ADDRESS = '0x000000000000000000000000000000000000dEaD' as const;

export const SUPPORTED_CHAINS = {
  // ─── TIER 1: Largest EVM ecosystems ───
  ethereum: {
    id: 1,
    name: 'Ethereum',
    symbol: 'ETH',
    color: '#627eea',
    explorer: 'https://etherscan.io',
    rpcUrl: 'https://cloudflare-eth.com',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  bnb: {
    id: 56,
    name: 'BNB Chain',
    symbol: 'BNB',
    color: '#f0b90b',
    explorer: 'https://bscscan.com',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  polygon: {
    id: 137,
    name: 'Polygon',
    symbol: 'POL',
    color: '#8247e5',
    explorer: 'https://polygonscan.com',
    rpcUrl: 'https://polygon-rpc.com',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  avalanche: {
    id: 43114,
    name: 'Avalanche',
    symbol: 'AVAX',
    color: '#e84142',
    explorer: 'https://snowtrace.io',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  // ─── TIER 2: Ethereum L2s ───
  arbitrum: {
    id: 42161,
    name: 'Arbitrum',
    symbol: 'ETH',
    color: '#12aaff',
    explorer: 'https://arbiscan.io',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  optimism: {
    id: 10,
    name: 'Optimism',
    symbol: 'ETH',
    color: '#ff0420',
    explorer: 'https://optimistic.etherscan.io',
    rpcUrl: 'https://mainnet.optimism.io',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  base: {
    id: 8453,
    name: 'Base',
    symbol: 'ETH',
    color: '#0052ff',
    explorer: 'https://basescan.org',
    rpcUrl: 'https://mainnet.base.org',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  zksync: {
    id: 324,
    name: 'zkSync Era',
    symbol: 'ETH',
    color: '#4e529a',
    explorer: 'https://explorer.zksync.io',
    rpcUrl: 'https://mainnet.era.zksync.io',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  linea: {
    id: 59144,
    name: 'Linea',
    symbol: 'ETH',
    color: '#61dfff',
    explorer: 'https://lineascan.build',
    rpcUrl: 'https://rpc.linea.build',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  scroll: {
    id: 534352,
    name: 'Scroll',
    symbol: 'ETH',
    color: '#eeb96a',
    explorer: 'https://scrollscan.com',
    rpcUrl: 'https://rpc.scroll.io',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  polygonzkevm: {
    id: 1101,
    name: 'Polygon zkEVM',
    symbol: 'ETH',
    color: '#7b3fe4',
    explorer: 'https://zkevm.polygonscan.com',
    rpcUrl: 'https://zkevm-rpc.com',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  mantle: {
    id: 5000,
    name: 'Mantle',
    symbol: 'MNT',
    color: '#000000',
    explorer: 'https://mantlescan.xyz',
    rpcUrl: 'https://rpc.mantle.xyz',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  blast: {
    id: 81457,
    name: 'Blast',
    symbol: 'ETH',
    color: '#fcfc03',
    explorer: 'https://blastscan.io',
    rpcUrl: 'https://rpc.blast.io',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  // ─── TIER 3: Alt L1s & other chains ───
  fantom: {
    id: 250,
    name: 'Fantom',
    symbol: 'FTM',
    color: '#1969ff',
    explorer: 'https://ftmscan.com',
    rpcUrl: 'https://rpc.ftm.tools',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  cronos: {
    id: 25,
    name: 'Cronos',
    symbol: 'CRO',
    color: '#002d74',
    explorer: 'https://cronoscan.com',
    rpcUrl: 'https://evm.cronos.org',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  gnosis: {
    id: 100,
    name: 'Gnosis',
    symbol: 'xDAI',
    color: '#04795b',
    explorer: 'https://gnosisscan.io',
    rpcUrl: 'https://rpc.gnosischain.com',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  celo: {
    id: 42220,
    name: 'Celo',
    symbol: 'CELO',
    color: '#35d07f',
    explorer: 'https://celoscan.io',
    rpcUrl: 'https://forno.celo.org',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  metis: {
    id: 1088,
    name: 'Metis',
    symbol: 'METIS',
    color: '#00d7c3',
    explorer: 'https://andromeda-explorer.metis.io',
    rpcUrl: 'https://andromeda.metis.io/?owner=1088',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L2',
  },
  moonbeam: {
    id: 1284,
    name: 'Moonbeam',
    symbol: 'GLMR',
    color: '#e1147b',
    explorer: 'https://moonscan.io',
    rpcUrl: 'https://rpc.api.moonbeam.network',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  kava: {
    id: 2222,
    name: 'Kava',
    symbol: 'KAVA',
    color: '#ff433e',
    explorer: 'https://kavascan.com',
    rpcUrl: 'https://evm.kava.io',
    burnAddress: EVM_BURN_ADDRESS,
    type: 'evm' as const,
    category: 'L1',
  },
  // ─── NON-EVM ───
  solana: {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    color: '#9945ff',
    explorer: 'https://solscan.io',
    rpcUrl: 'https://api.mainnet-beta.solana.com',
    burnAddress: '1nc1nerator11111111111111111111111111111111',
    type: 'solana' as const,
    category: 'L1',
  },
} as const;

export type ChainKey = keyof typeof SUPPORTED_CHAINS;
export type Chain = (typeof SUPPORTED_CHAINS)[ChainKey];

export interface Asset {
  id: string;
  name: string;
  symbol: string;
  type: 'token' | 'nft';
  balance: string;
  balanceRaw: bigint;
  decimals: number;
  contractAddress: string;
  usdValue: string;
  logoUrl?: string;
  tokenId?: string; // for NFTs
  chain: ChainKey;
}
